# Generated by Django 4.2.2 on 2023-06-20 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
        ('fabricantes', '0002_fabricante_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estados.estado'),
        ),
    ]
